### PR TITLE
Add ODB2 PID query support.

### PR DESCRIPTION
**Pull request by streber42**
I don't have an easy way to test this, but I think this is what you were asking for.

### CODE REVIEW

**Comment by jsphuebner** [comment]
Nice integration, thanks. Will see if I can test it with CAN commander

**Comment by jsphuebner** [comment]
Tested with my cheap China OBD2 adapter and VAG K CAN Commander.
When I press "Open Device" it sends out some 0x200 message:
obd2

Does the reply to that need to be implemented in the obd2 module?

**Comment by streber42** [comment]
You probably need to tell your app to use a different header or module (different apps have called it different things).  The broadcast/default is is 0x7DF, but can be 0x7E0-0x7E8 if you have more than 1 ECUs on the bus.  Then the reply should be the listen ID + 8;

The first bye is the length of the message, so that is it asking for "Engine Speed".

**Comment by streber42** [comment]
Or just update the OBD2_PID_REQUEST/REPLY defines to match what you are seeing.

**Comment by jsphuebner** [comment]
Ok, will test more later

**Pull request merged**
